from __future__ import annotations

from pathlib import Path
from typing import Any

try:
    from rdkit import Chem
    from rdkit.Chem import AllChem
except ImportError as exc:  # pragma: no cover
    raise ImportError("RDKit is required for preopt.py") from exc


def embed_and_optimize_smiles(smiles: str, force_field: str = "UFF") -> Chem.Mol:
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"Invalid SMILES: {smiles}")

    mol = Chem.AddHs(mol)
    status = AllChem.EmbedMolecule(mol, AllChem.ETKDGv3())
    if status != 0:
        raise RuntimeError(f"Embedding failed for SMILES: {smiles}")

    force_field = force_field.upper()
    if force_field == "MMFF":
        if AllChem.MMFFHasAllMoleculeParams(mol):
            AllChem.MMFFOptimizeMolecule(mol)
        else:
            AllChem.UFFOptimizeMolecule(mol)
    else:
        AllChem.UFFOptimizeMolecule(mol)

    return mol


def rdkit_mol_to_ase_atoms(mol: Chem.Mol) -> Any:
    try:
        from ase import Atoms
    except ImportError as exc:  # pragma: no cover
        raise ImportError("ASE is required for ML pre-relaxation workflows.") from exc

    conf = mol.GetConformer()
    symbols = [atom.GetSymbol() for atom in mol.GetAtoms()]
    coords = []
    for i in range(mol.GetNumAtoms()):
        pos = conf.GetAtomPosition(i)
        coords.append([pos.x, pos.y, pos.z])
    return Atoms(symbols=symbols, positions=coords)


def ase_atoms_to_rdkit_mol(template_mol: Chem.Mol, atoms: Any) -> Chem.Mol:
    mol = Chem.Mol(template_mol)
    conf = mol.GetConformer()
    for i, pos in enumerate(atoms.get_positions()):
        conf.SetAtomPosition(i, pos)
    return mol


def get_ml_calculator(backend: str, **kwargs: Any) -> Any:
    backend_key = backend.strip().lower()

    if backend_key == "uma":
        try:
            from fairchem.core import pretrained_models
        except ImportError as exc:  # pragma: no cover
            raise ImportError(
                "UMA backend requested, but fairchem is not installed."
            ) from exc
        model_name = kwargs.pop("model_name", "uma-s-1p1")
        return pretrained_models(model_name, **kwargs)

    if backend_key == "mace":
        try:
            from mace.calculators import mace_mp
        except ImportError as exc:  # pragma: no cover
            raise ImportError("MACE backend requested, but mace is not installed.") from exc
        model = kwargs.pop("model", "medium")
        device = kwargs.pop("device", "cpu")
        return mace_mp(model=model, device=device, **kwargs)

    if backend_key in {"orb", "orb-v2", "orb_models"}:
        try:
            from orb_models.forcefield import pretrained
        except ImportError as exc:  # pragma: no cover
            raise ImportError(
                "ORB backend requested, but orb-models is not installed."
            ) from exc
        orb_model = kwargs.pop("model", "orb-v2")
        device = kwargs.pop("device", "cpu")
        return pretrained.orb_v2(device=device) if orb_model == "orb-v2" else pretrained.orb_d3_v2(device=device)

    raise ValueError(f"Unsupported ML backend: {backend}")


def preoptimize_with_ml_potential(
    mol: Chem.Mol,
    *,
    backend: str = "uma",
    fmax: float = 0.05,
    steps: int = 200,
    calculator: Any | None = None,
    **calculator_kwargs: Any,
) -> Chem.Mol:
    try:
        from ase.optimize import BFGS
    except ImportError as exc:  # pragma: no cover
        raise ImportError("ASE is required for ML pre-relaxation workflows.") from exc

    atoms = rdkit_mol_to_ase_atoms(mol)
    atoms.calc = calculator if calculator is not None else get_ml_calculator(backend, **calculator_kwargs)

    optimizer = BFGS(atoms, logfile=None)
    optimizer.run(fmax=fmax, steps=steps)

    return ase_atoms_to_rdkit_mol(mol, atoms)


def mol_to_xyz_block(mol: Chem.Mol, comment: str = "Generated by RDKit") -> str:
    conf = mol.GetConformer()
    lines = [str(mol.GetNumAtoms()), comment]
    for atom in mol.GetAtoms():
        pos = conf.GetAtomPosition(atom.GetIdx())
        lines.append(f"{atom.GetSymbol()} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")
    return "\n".join(lines) + "\n"


def write_xyz(mol: Chem.Mol, out_path: str | Path, comment: str = "Generated by RDKit") -> Path:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(mol_to_xyz_block(mol, comment=comment))
    return out_path
